### ISSUE TITLE
Mediator missing comparative template models

### ISSUE THREAD

**Issue by tomgoddard** [ihmwg/IHM-dictionary#29] opened 2017-03-29 20:25 UTC
The mediator example lists 6 comparative models in the ihm_starting_model_details table but there is no ihm_starting_comparative_models table giving the templates.

_ihm_starting_model_details.ordinal_id
_ihm_starting_model_details.entity_id
_ihm_starting_model_details.entity_description
_ihm_starting_model_details.asym_id
_ihm_starting_model_details.seq_id_begin
_ihm_starting_model_details.seq_id_end
_ihm_starting_model_details.starting_model_source
_ihm_starting_model_details.starting_model_db_name
_ihm_starting_model_details.starting_model_db_code
_ihm_starting_model_details.starting_model_auth_asym_id
_ihm_starting_model_details.starting_model_sequence_offset
_ihm_starting_model_details.starting_model_id
_ihm_starting_model_details.dataset_list_id
1 1 med6 A 1 192 'experimental model' PDB 4GWP G 0 med6-m1 1
2 2 med8 B 23 214 'experimental model' PDB 4GWP C 0 med8-m1 1
3 3 med11 C 4 115 'experimental model' PDB 4GWP A 0 med11-m1 1
4 4 med17 D 182 687 'experimental model' PDB 4GWP B 0 med17-m1 1
5 5 med18 E 2 301 'experimental model' PDB 4GWP E 0 med18-m1 1
6 6 med20 F 2 210 'experimental model' PDB 4GWP F 0 med20-m1 1
7 7 med22 G 1 121 'experimental model' PDB 4GWP D 0 med22-m1 1
8 8 med4 H 37 127 'comparative model' ? ? D 0 med4-m1 2
9 9 med7 I 12 206 'comparative model' ? ? G 0 med7-m1 2
10 10 med9 J 65 149 'comparative model' ? ? I 0 med9-m1 2
11 11 med31 K 19 110 'comparative model' ? ? Z 0 med31-m1 2
12 12 med21 L 2 128 'comparative model' ? ? U 0 med21-m1 2
13 21 med16 U 8 538 'comparative model' ? ? ' ' 0 med16-m1 3

**Comment by benmwebb** [comment] 2017-03-29 20:26
That's because we don't know what the templates were.

**Comment by brindakv** [comment] 2017-03-29 20:28
Ben, please clarify. What do you mean by not knowing what the templates are? How were the comparative models obtained?

**Comment by benmwebb** [comment] 2017-03-29 20:30
All I've been given (and all that's in the GitHub repository) is the output PDB file - no information on how it was generated - and so the mmCIF output reflects that. I'll have to ask the exosome modeling guys if they can provide this.

**Comment by benmwebb** [comment] 2017-03-29 20:36
BTW, just for reference, this is mediator, not exosome.

**Comment by brindakv** [comment] 2017-03-29 20:40
Could we get this information from the publication?

**Comment by benmwebb** [comment] 2017-03-29 20:47
The publication states that one is some kind of docking and the other is a homology model, but ideally we need the actual input files, and I didn't see those anywhere in the supplemental info.

**Comment by benmwebb** [comment] 2017-04-14 01:29
OK, med16 is straightened out. It's a Phyre2 comparative model, so I've added template information to the mediator `.cif` output (will be in the next update). The remaining subunits are a bit tricky though - each is a single chain in `cr_mid_fullmed10.pdb` (which is a multi-chain PDB). But this is not a comparative model, integrative model, or experimental model. It's a mashup model:

- Chains A, B, and C are taken verbatim from a comparative model published elsewhere (just coordinates, in PDB format, in the supplemental info of another paper)
- The N terminus of chain D is PDB structure 1abc, but rotated and translated to fit in the same reference frame as the comparative model
- The C terminus of chain D is PDB structure 2xyz, also rotated and translated.

Seems there are three ways we can handle this:

1. Pretend it's a comparative model (which is what we do currently) based on templates 1abc, 2xyz and other-papers-doi. The drawback here is that it isn't "really" a comparative model, all of the templates are 100% identical, and one of the templates is itself a comparative model.
2. Split the starting model into three separate datasets, one for each model. Point each one to the same `cr_mid_fullmed10.pdb` file in the repository (`file_id`), but populate `ihm_related_datasets` so that each derived dataset points back to the original data (the two PDB IDs, and the DOI). (We have to split into three datasets because if we keep one dataset for the whole file and just give it three parents, we don't know which part of the structure is derived from each parent.) Having multiple datasets that point to the same file looks a little weird but seems to be allowed by the dictionary. Is this correct @brindakv?
3. Actually split the `cr_mid_fullmed10.pdb` file into three separate files. I would prefer to avoid this because I want to preserve what was actually done as closely as possible, but IMP doesn't care whether two chains come from the same PDB or two different PDBs, so it won't affect the modeling.

Opinions?

**Comment by benmwebb** [comment] 2017-04-14 23:36
I think I'll have no choice but to split it into three separate files. The problem is that the real data looks like this

- `med7c_med21` dataset: PDB file in the repository containing half of the G chain, plus the U chain, which are transformed from 1YKH:A and 1YKH:B
- `med7n_med31` dataset: PDB file in the repository containing other half of G chain, plus Z chain, which are transformed from 3FBI:A and 3FBI:B
- `med4_med9` dataset: PDB file in the repository containing D, I, J chains (it also contains a structure for med10 that wasn't used in our study). This comes verbatim from Lariviere et al.

I can certainly say that the `med7c_med21` dataset is derived from 1YKH in PDB, but there's no way for me to say in the dictionary that G->A and U->B. I could put in the notes that we renamed the chains. But I would prefer to actually rename them back to the original PDB chain IDs. (A non-crazy person, or a software package, would probably make the assumption that the chain IDs in our transformed experimental model match those in the original PDB entry.) I can't do this without splitting the files because then I'd end up with two chain Bs. So splitting seems the way to go.

**Comment by brindakv** [comment] 2017-04-17 15:10
@benmwebb, I think it is best to split the model into three separate files. Although IMP does not have this information and it does not preserve what was actually done, in this case this is the better solution. You may also want to recommend to future users of IMP that starting models retain as much as information as possible.

**Closed** 2017-04-19 22:08 UTC
